# Load default .tmux.conf
source-file ~/.tmux.conf

# vim
new-session -s blog -n vim -d -c ~/code/ngeraedts.github.io
send-keys 'vim .' Enter

# create second window
new-window -n zsh -c ~/code/ngeraedts.github.io

# Create split layout
split-window -h -p 50 -c ~/code/ngeraedts.github.io
split-window -v -p 50 -c ~/code/ngeraedts.github.io

# reselect window 1 (the one with vim)
select-window -t vim
